# -*- coding: utf-8 -*-
"""
Created on Wed Sep 20 23:53:41 2017

@author: pc
"""

import os,time
print("                        ")
print("                        ")
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
print("                        ")
print("                        ")
time.sleep(0.1)
i=os.system('cls')
print("                        ")
print("                        ")
print("                        ")
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
print("                        ")
time.sleep(0.1)
i=os.system('cls')
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
time.sleep(0.1)
i=os.system('cls')
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
time.sleep(0.1)
i=os.system('cls')
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
print("  # #    #     #    #   ")
time.sleep(0.1)
i=os.system('cls')
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
time.sleep(0.1)
i=os.system('cls')
print("#     #  #     #    #   ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
time.sleep(0.1)
i=os.system('cls')
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
time.sleep(0.1)
i=os.system('cls')
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("#      # #     # #     #")
time.sleep(0.1)
i=os.system('cls')
print("   #     #######    #   ")
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
time.sleep(0.1)
i=os.system('cls')
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
time.sleep(0.1)
i=os.system('cls')
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
time.sleep(0.1)
i=os.system('cls')
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
print("                        ")
print("                        ")
print("                        ")
print("                        ")
time.sleep(0.1)
i=os.system('cls')
print("                        ")
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
print("                        ")
print("                        ")
print("                        ")
time.sleep(0.1)
i=os.system('cls')
print("                        ")
print("                        ")
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
print("                        ")
print("                        ")
time.sleep(0.1)
i=os.system('cls')
print("                        ")
print("                        ")
print("#      # #     # #     #")
print(" #    #  #     #  #   # ")
print("  #  #   #     #   # #  ")
print("   #     #######    #   ")
print("  # #    #     #    #   ")
print(" #   #   #     #    #   ")
print("#     #  #     #    #   ")
print("                        ")
print("                        ")
time.sleep(0.05)
i=os.system('cls')
print("                         ")
print("                         ")
print("#      # #     #  #     #")
print(" #    #  #     #   #   # ")
print("  #  #   #     #    # #  ")
print("   #     #######     #   ")
print("  # #    #     #     #   ")
print(" #   #   #     #     #   ")
print("#     #  #     #     #   ")
print("                         ")
print("                         ")
time.sleep(0.05)
i=os.system('cls')
print("                          ")
print("                          ")
print("#      # #     #   #     #")
print(" #    #  #     #    #   # ")
print("  #  #   #     #     # #  ")
print("   #     #######      #   ")
print("  # #    #     #      #   ")
print(" #   #   #     #      #   ")
print("#     #  #     #      #   ")
print("                          ")
print("                          ")
time.sleep(0.05)
i=os.system('cls')
print("                           ")
print("                           ")
print("#      # #     #    #     #")
print(" #    #  #     #     #   # ")
print("  #  #   #     #      # #  ")
print("   #     #######       #   ")
print("  # #    #     #       #   ")
print(" #   #   #     #       #   ")
print("#     #  #     #       #   ")
print("                           ")
print("                           ")
time.sleep(0.05)
i=os.system('cls')
print("                            ")
print("                            ")
print("#      # #     #     #     #")
print(" #    #  #     #      #   # ")
print("  #  #   #     #       # #  ")
print("   #     #######        #   ")
print("  # #    #     #        #   ")
print(" #   #   #     #        #   ")
print("#     #  #     #        #   ")
print("                            ")
print("                            ")
time.sleep(0.05)
i=os.system('cls')
print("                             ")
print("                             ")
print("#      # #     #      #     #")
print(" #    #  #     #       #   # ")
print("  #  #   #     #        # #  ")
print("   #     #######         #   ")
print("  # #    #     #         #   ")
print(" #   #   #     #         #   ")
print("#     #  #     #         #   ")
print("                             ")
print("                             ")
time.sleep(0.05)
i=os.system('cls')
print("                              ")
print("                              ")
print("#      # #     #       #     #")
print(" #    #  #     #        #   # ")
print("  #  #   #     #         # #  ")
print("   #     #######          #   ")
print("  # #    #     #          #   ")
print(" #   #   #     #          #   ")
print("#     #  #     #          #   ")
print("                              ")
print("                              ")
time.sleep(0.05)
i=os.system('cls')
print("                               ")
print("                               ")
print("#      # #     #        #     #")
print(" #    #  #     #         #   # ")
print("  #  #   #     #          # #  ")
print("   #     #######           #   ")
print("  # #    #     #           #   ")
print(" #   #   #     #           #   ")
print("#     #  #     #           #   ")
print("                               ")
print("                               ")
time.sleep(0.05)
i=os.system('cls')
print("                                ")
print("                                ")
print("#      # #     #         #     #")
print(" #    #  #     #          #   # ")
print("  #  #   #     #           # #  ")
print("   #     #######            #   ")
print("  # #    #     #            #   ")
print(" #   #   #     #            #   ")
print("#     #  #     #            #   ")
print("                                ")
print("                                ")
time.sleep(0.05)
i=os.system('cls')
print("                                 ")
print("                                 ")
print("#      # #     #          #     #")
print(" #    #  #     #           #   # ")
print("  #  #   #     #            # #  ")
print("   #     #######             #   ")
print("  # #    #     #             #   ")
print(" #   #   #     #             #   ")
print("#     #  #     #             #   ")
print("                                 ")
print("                                 ")
time.sleep(0.05)
i=os.system('cls')
print("                                  ")
print("                                  ")
print("#      # #     #           #     #")
print(" #    #  #     #            #   # ")
print("  #  #   #     #             # #  ")
print("   #     #######              #   ")
print("  # #    #     #              #   ")
print(" #   #   #     #              #   ")
print("#     #  #     #              #   ")
print("                                  ")
print("                                  ")
time.sleep(0.05)
i=os.system('cls')
print("                                   ")
print("                                   ")
print("#      # #     #            #     #")
print(" #    #  #     #             #   # ")
print("  #  #   #     #              # #  ")
print("   #     #######               #   ")
print("  # #    #     #               #   ")
print(" #   #   #     #               #   ")
print("#     #  #     #               #   ")
print("                                   ")
print("                                   ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      # #     #             #     #")
print(" #    #  #     #              #   # ")
print("  #  #   #     #               # #  ")
print("   #     #######                #   ")
print("  # #    #     #                #   ")
print(" #   #   #     #                #   ")
print("#     #  #     #                #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #  #     #            #     #")
print(" #    #   #     #             #   # ")
print("  #  #    #     #              # #  ")
print("   #      #######               #   ")
print("  # #     #     #               #   ")
print(" #   #    #     #               #   ")
print("#     #   #     #               #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #   #     #           #     #")
print(" #    #    #     #            #   # ")
print("  #  #     #     #             # #  ")
print("   #       #######              #   ")
print("  # #      #     #              #   ")
print(" #   #     #     #              #   ")
print("#     #    #     #              #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #    #     #          #     #")
print(" #    #     #     #           #   # ")
print("  #  #      #     #            # #  ")
print("   #        #######             #   ")
print("  # #       #     #             #   ")
print(" #   #      #     #             #   ")
print("#     #     #     #             #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #     #     #         #     #")
print(" #    #      #     #          #   # ")
print("  #  #       #     #           # #  ")
print("   #         #######            #   ")
print("  # #        #     #            #   ")
print(" #   #       #     #            #   ")
print("#     #      #     #            #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #      #     #        #     #")
print(" #    #       #     #         #   # ")
print("  #  #        #     #          # #  ")
print("   #          #######           #   ")
print("  # #         #     #           #   ")
print(" #   #        #     #           #   ")
print("#     #       #     #           #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #       #     #       #     #")
print(" #    #        #     #        #   # ")
print("  #  #         #     #         # #  ")
print("   #           #######          #   ")
print("  # #          #     #          #   ")
print(" #   #         #     #          #   ")
print("#     #        #     #          #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #        #     #      #     #")
print(" #    #         #     #       #   # ")
print("  #  #          #     #        # #  ")
print("   #            #######         #   ")
print("  # #           #     #         #   ")
print(" #   #          #     #         #   ")
print("#     #         #     #         #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #         #     #     #     #")
print(" #    #          #     #      #   # ")
print("  #  #           #     #       # #  ")
print("   #             #######        #   ")
print("  # #            #     #        #   ")
print(" #   #           #     #        #   ")
print("#     #          #     #        #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #          #     #    #     #")
print(" #    #           #     #     #   # ")
print("  #  #            #     #      # #  ")
print("   #              #######       #   ")
print("  # #             #     #       #   ")
print(" #   #            #     #       #   ")
print("#     #           #     #       #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #           #     #   #     #")
print(" #    #            #     #    #   # ")
print("  #  #             #     #     # #  ")
print("   #               #######      #   ")
print("  # #              #     #      #   ")
print(" #   #             #     #      #   ")
print("#     #            #     #      #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #            #     #  #     #")
print(" #    #             #     #   #   # ")
print("  #  #              #     #    # #  ")
print("   #                #######     #   ")
print("  # #               #     #     #   ")
print(" #   #              #     #     #   ")
print("#     #             #     #     #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("#      #             #     # #     #")
print(" #    #              #     #  #   # ")
print("  #  #               #     #   # #  ")
print("   #                 #######    #   ")
print("  # #                #     #    #   ")
print(" #   #               #     #    #   ")
print("#     #              #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print(" #      #            #     # #     #")
print("  #    #             #     #  #   # ")
print("   #  #              #     #   # #  ")
print("    #                #######    #   ")
print("   # #               #     #    #   ")
print("  #   #              #     #    #   ")
print(" #     #             #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("  #      #           #     # #     #")
print("   #    #            #     #  #   # ")
print("    #  #             #     #   # #  ")
print("     #               #######    #   ")
print("    # #              #     #    #   ")
print("   #   #             #     #    #   ")
print("  #     #            #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("   #      #          #     # #     #")
print("    #    #           #     #  #   # ")
print("     #  #            #     #   # #  ")
print("      #              #######    #   ")
print("     # #             #     #    #   ")
print("    #   #            #     #    #   ")
print("   #     #           #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("    #      #         #     # #     #")
print("     #    #          #     #  #   # ")
print("      #  #           #     #   # #  ")
print("       #             #######    #   ")
print("      # #            #     #    #   ")
print("     #   #           #     #    #   ")
print("    #     #          #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("     #      #        #     # #     #")
print("      #    #         #     #  #   # ")
print("       #  #          #     #   # #  ")
print("        #            #######    #   ")
print("       # #           #     #    #   ")
print("      #   #          #     #    #   ")
print("     #     #         #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("      #      #       #     # #     #")
print("       #    #        #     #  #   # ")
print("        #  #         #     #   # #  ")
print("         #           #######    #   ")
print("        # #          #     #    #   ")
print("       #   #         #     #    #   ")
print("      #     #        #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("       #      #      #     # #     #")
print("        #    #       #     #  #   # ")
print("         #  #        #     #   # #  ")
print("          #          #######    #   ")
print("         # #         #     #    #   ")
print("        #   #        #     #    #   ")
print("       #     #       #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("        #      #     #     # #     #")
print("         #    #      #     #  #   # ")
print("          #  #       #     #   # #  ")
print("           #         #######    #   ")
print("          # #        #     #    #   ")
print("         #   #       #     #    #   ")
print("        #     #      #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("         #      #    #     # #     #")
print("          #    #     #     #  #   # ")
print("           #  #      #     #   # #  ")
print("            #        #######    #   ")
print("           # #       #     #    #   ")
print("          #   #      #     #    #   ")
print("         #     #     #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("          #      #   #     # #     #")
print("           #    #    #     #  #   # ")
print("            #  #     #     #   # #  ")
print("             #       #######    #   ")
print("            # #      #     #    #   ")
print("           #   #     #     #    #   ")
print("          #     #    #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("           #      #  #     # #     #")
print("            #    #   #     #  #   # ")
print("             #  #    #     #   # #  ")
print("              #      #######    #   ")
print("             # #     #     #    #   ")
print("            #   #    #     #    #   ")
print("           #     #   #     #    #   ")
print("                                    ")
print("                                    ")
time.sleep(0.05)
i=os.system('cls')
print("                                    ")
print("                                    ")
print("            #      # #     # #     #")
print("             #    #  #     #  #   # ")
print("              #  #   #     #   # #  ")
print("               #     #######    #   ")
print("              # #    #     #    #   ")
print("             #   #   #     #    #   ")
print("            #     #  #     #    #   ")
print("                                    ")
print("                                    ")
